### ISSUE TITLE
Inference shouldn't just return MAP

### ISSUE THREAD

**Issue by barkls** [phys201/optical_lattice#15]
MCMC calculations give you a full collection of samples/traces, so it's a bit of a waste to throw all that out and just return the MAP value. The width of the distribution in P tells you about how informative your data is. You will also want access to all the samples for marginalizing if you add more parameters such as the width of the Gaussian.

**Comment by sfozturk61** [comment]
I agree this is the most primitive model that works, it only knows the count locations and tries to tell if it comes from a Gaussian or a uniform distribution. It certainly does not work with the real data. We are now working on a next-gen model that also takes into account, for instance, total photon counts. That would also help because in principle we know how many photons an atom emits and this information (other than just the locations) helps us to further solidify if there is an or not. One can think of other parameters such as the center of the site and the width of the PSF.

**Comment by barkls** [comment]
I wasn't trying to make a point about model complexity or accuracy here.

In general, the reason MCMC is a powerful technique is that it gives you the full posterior distribution. Right now you are throwing all of that information away by returning a point estimate for the peak of the distribution. Even if that's the part of the distribution that you're most interested in right now, it would be nice to have access to all the samples, since there's currently no way to retrieve them.

**Comment by sfozturk61** [comment]
Next gen model does not only look at the MAP value it uses sampling.
