### ISSUE TITLE
Interpretation of inferred parameter "P"

### ISSUE THREAD

**Issue by barkls** [phys201/optical_lattice#16]
The tutorial notebook states that *P* is the probability of a lattice site containing an atom, but I'm not convinced that's the correct interpretation from looking at `analysis_models.py`. Instead, it seems like *P* is the fraction of photons that came from the atom as opposed to the background.

In this case a value of *P*=0 can be safely interpreted as the absence of an atom, but *P*=0.1 should properly be interpreted as the presence of an atom with a strong background fluorescence. You would never expect to see *P*=1 unless there was no background.

Am I missing something here? It seems like there should be an extra step to convert the fraction of photons coming from the atom to the presence or absence of the atom.

**Comment by sfozturk61** [comment]
Your understanding is correct. P is the fraction of photons that came from the atom. After this, a threshold for P should be set to tell if a site is occupied or not. And then by comparing the result to the actual lattice distribution the fidelity can be calculated.

**Comment by vnmanoharan** [comment]
I'd recommend spending some time deriving the likelihood function for the mixture model so that what you're trying to infer is analogous to the q_i in HBL.  That's what you're interested in.  If you can write down some equations for your derivation and add them to the notebook, we can go over them sometime in the next few days. 

In that likelihood derivation, you'll want to write down an expression that is a function of all the sites (not just one) and, if you can, includes both the data on the counts and the spatial distribution of events.

**Comment by barkls** [comment]
On that note, I think it would be easiest to first consider datasets
without any background signal. If you come up with a generative model for
just the signal depending on whether an atom is present or not at each
site, you can probably treat the background as a special type of noise that
appears in the likelihood expression but not in the forward function.

**Comment by barkls** [comment]
Note that by special I really mean "non-gaussian". There's nothing special
about treating noise in the likelihood.

**Comment by sfozturk61** [comment]
We updated our model. Now there is only one P value for the whole lattice and it corresponds to the probability that a site is occupied. For instance if there are N = 100 sites and 50 atoms, P is around 0.5. In the new model, we have an (N, N) array of q values from a Bernouilli distribution with probability P. Each q number can be 0 or 1 and this number tells if a lattice site occupied or not.
